[tools]
python = "3.14.5"
uv = "latest"

[tasks.init]
description = "Initialize the environment"
run = "uv sync"

[tasks.start]
description = "Run the CLI"
run = "uv run python -m kvk_data_service_experiment.cli"

[tasks.lint]
description = "Run lint check"
run = "uv run ruff check --fix src/ test/"

[tasks.format]
description = "Run format check"
run = "uv run ruff format src/ test/"

[tasks.types]
description = "Run type check"
run = "uv run pyright src/"

[tasks.test]
description = "Run unit tests"
run = "uv run pytest test/"

[tasks."test:all"]
description = "Run all tests"
run = "uv run pytest -m '' test/"

[tasks."test:integration"]
description = "Run integration tests"
run = "uv run pytest -m integration test/"
